"""add note pinned status

Revision ID: d1fc7bff0a31
Revises: 74860622ff26
Create Date: 2026-08-13 00:28:46.237002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1fc7bff0a31'
down_revision: Union[str, Sequence[str], None] = '74860622ff26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('is_pinned', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('notes', 'is_pinned', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'is_pinned')
    # ### end Alembic commands ###
